-- Migration: Create Events Table
-- Description: Creates events table for managing events and achievements
-- Date: 2025-01-20

-- Create events table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    date DATE NOT NULL,
    time VARCHAR(100),
    location VARCHAR(255) NOT NULL,
    venue VARCHAR(255),
    address TEXT,
    type VARCHAR(50) NOT NULL, -- Conference, Summit, Workshop, Forum, Program, Meeting
    category VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'upcoming', -- upcoming, completed, cancelled
    description TEXT,
    full_description LONGTEXT,
    attendees INT DEFAULT 0,
    image VARCHAR(500),
    registration_open BOOLEAN DEFAULT FALSE,
    registration_deadline DATE,
    price VARCHAR(100),
    speakers JSON, -- Array of speaker objects
    agenda JSON, -- Array of agenda items
    requirements JSON, -- Array of requirements
    meta_title VARCHAR(255),
    meta_description TEXT,
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    INDEX idx_date (date),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_status (status),
    INDEX idx_type (type),
    INDEX idx_category (category),
    INDEX idx_slug (slug),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert sample data
INSERT INTO events (
    title, slug, date, time, location, venue, address, type, category, status,
    description, full_description, attendees, image, registration_open,
    registration_deadline, price, speakers, agenda, requirements,
    is_active, is_featured
) VALUES
(
    'GCX Annual Conference 2025',
    'gcx-annual-conference-2025',
    '2025-12-15',
    '9:00 AM - 5:00 PM',
    'Accra, Ghana',
    'Kempinski Hotel Gold Coast City',
    'Ridge, Accra, Ghana',
    'Conference',
    'Conference',
    'upcoming',
    'The Ghana Commodity Exchange Annual Conference will bring together industry leaders, farmers, and stakeholders to discuss the future of commodity trading in Ghana.',
    'The Ghana Commodity Exchange Annual Conference 2025 is our flagship event that brings together over 500 industry leaders, farmers, traders, policymakers, and stakeholders from across Ghana and the West African region. This year''s conference focuses on three key themes:\n\n**Digital Transformation in Agriculture**\n- Leveraging technology to improve commodity trading\n- Digital platforms for farmer-market connectivity\n- Blockchain and traceability in agricultural supply chains\n\n**Sustainable Agriculture Practices**\n- Climate-smart farming techniques\n- Sustainable commodity production\n- Environmental impact reduction strategies\n\n**Market Innovation and Development**\n- New trading mechanisms and instruments\n- International market integration\n- Policy frameworks for commodity exchange growth\n\nThe conference will feature keynote presentations from industry experts, panel discussions, networking sessions, and practical workshops.',
    500,
    '/Picture3.png',
    TRUE,
    '2025-12-10',
    'Free',
    '[{"name":"Dr. Kofi Adomakoh","title":"CEO, Ghana Commodity Exchange","image":"/Picture3.png"},{"name":"Hon. Dr. Owusu Afriyie Akoto","title":"Minister of Food and Agriculture","image":"/Picture3.png"},{"name":"Ms. Elizabeth Ohene","title":"Board Chair, GCX","image":"/Picture3.png"}]',
    '[{"time":"9:00 AM","session":"Registration and Welcome Coffee"},{"time":"9:30 AM","session":"Opening Ceremony and Keynote Address"},{"time":"10:30 AM","session":"Panel Discussion: Digital Agriculture"},{"time":"12:00 PM","session":"Networking Lunch"},{"time":"1:30 PM","session":"Workshop: Trading Strategies"},{"time":"3:00 PM","session":"Panel Discussion: Sustainable Practices"},{"time":"4:30 PM","session":"Closing Remarks and Awards"}]',
    '["Valid government-issued ID","Business card for networking","Laptop or tablet for workshops (optional)"]',
    TRUE,
    TRUE
),
(
    'Agricultural Technology Summit 2025',
    'agricultural-tech-summit-2025',
    '2025-11-20',
    '8:00 AM - 6:00 PM',
    'Kumasi, Ghana',
    'Golden Tulip Kumasi City',
    'Asokore Mampong, Kumasi, Ghana',
    'Summit',
    'Summit',
    'upcoming',
    'Exploring cutting-edge agricultural technologies and their impact on commodity trading and market development.',
    'The Agricultural Technology Summit 2025 is a comprehensive event focused on the intersection of technology and agriculture in Ghana. This summit brings together tech innovators, agricultural experts, and commodity traders to explore how emerging technologies can revolutionize the agricultural sector.\n\n**Key Focus Areas:**\n- Precision agriculture and IoT applications\n- Mobile technology for farmers\n- Data analytics in commodity trading\n- AI and machine learning in agriculture\n- Fintech solutions for agricultural finance\n\nThe summit will feature live demonstrations, technology showcases, and hands-on workshops where participants can interact with the latest agricultural technologies.',
    300,
    '/Picture3.png',
    TRUE,
    '2025-11-15',
    'GHS 50',
    '[{"name":"Dr. Kwame Asante","title":"Director, CSIR-Crops Research Institute","image":"/Picture3.png"},{"name":"Ms. Ama Serwaa","title":"CEO, AgriTech Solutions","image":"/Picture3.png"}]',
    '[{"time":"8:00 AM","session":"Registration and Technology Showcase"},{"time":"9:00 AM","session":"Opening Keynote: Future of AgTech"},{"time":"10:30 AM","session":"Panel: IoT in Agriculture"},{"time":"12:00 PM","session":"Lunch and Networking"},{"time":"1:30 PM","session":"Workshop: Mobile Apps for Farmers"},{"time":"3:00 PM","session":"Panel: Data Analytics"},{"time":"4:30 PM","session":"Closing and Awards"}]',
    '["Valid ID","Smartphone for app demonstrations","Interest in agricultural technology"]',
    TRUE,
    TRUE
),
(
    'Youth in Agriculture Program 2025',
    'youth-agriculture-program-2025',
    '2025-10-25',
    '9:00 AM - 4:00 PM',
    'Takoradi, Ghana',
    'Takoradi Technical University',
    'Takoradi, Western Region, Ghana',
    'Program',
    'Program',
    'upcoming',
    'Engaging young people in agriculture and commodity trading through education, mentorship, and practical training.',
    'The Youth in Agriculture Program 2025 is designed to inspire and educate the next generation of agricultural leaders and commodity traders in Ghana. This comprehensive program combines theoretical knowledge with hands-on practical experience.\n\n**Program Highlights:**\n- Interactive workshops on modern farming techniques\n- Commodity trading simulation exercises\n- Mentorship sessions with industry professionals\n- Field visits to successful farms and trading facilities\n- Networking opportunities with peers and industry leaders\n\nThe program is open to students, recent graduates, and young professionals aged 18-35 who are interested in pursuing careers in agriculture or commodity trading.',
    100,
    '/Picture3.png',
    TRUE,
    '2025-10-20',
    'Free',
    '[{"name":"Dr. Kwame Asante","title":"Director of Youth Programs, GCX","image":"/Picture3.png"},{"name":"Ms. Akosua Mensah","title":"Successful Young Farmer","image":"/Picture3.png"},{"name":"Mr. Kofi Boateng","title":"Commodity Trader","image":"/Picture3.png"}]',
    '[{"time":"9:00 AM","session":"Registration and Welcome"},{"time":"9:30 AM","session":"Introduction to Commodity Trading"},{"time":"10:30 AM","session":"Modern Farming Techniques Workshop"},{"time":"12:00 PM","session":"Lunch and Networking"},{"time":"1:00 PM","session":"Trading Simulation Exercise"},{"time":"2:30 PM","session":"Field Visit to Local Farm"},{"time":"4:00 PM","session":"Mentorship Session and Q&A"}]',
    '["Valid student ID or age verification","Interest in agriculture or trading","Notebook for taking notes","Comfortable clothing for field visit"]',
    TRUE,
    FALSE
),
(
    'GCX Annual Conference 2023',
    'gcx-annual-conference-2023',
    '2023-12-15',
    '9:00 AM - 5:00 PM',
    'Accra, Ghana',
    'Kempinski Hotel Gold Coast City',
    'Ridge, Accra, Ghana',
    'Conference',
    'Conference',
    'completed',
    'The Ghana Commodity Exchange Annual Conference brought together industry leaders, farmers, and stakeholders to discuss the future of commodity trading in Ghana.',
    'The 2023 GCX Annual Conference was a resounding success, bringing together over 500 participants from across Ghana and the West African region. The conference focused on building resilience in commodity trading and exploring new opportunities for market growth.\n\n**Key Achievements:**\n- Launched new digital trading platform\n- Signed 5 new international partnerships\n- Announced expansion to 3 new regions\n- Recognized outstanding farmers and traders\n\nThe event featured engaging panel discussions, practical workshops, and valuable networking opportunities.',
    500,
    '/Picture3.png',
    FALSE,
    NULL,
    'Free',
    '[{"name":"Dr. Kofi Adomakoh","title":"CEO, Ghana Commodity Exchange","image":"/Picture3.png"},{"name":"Hon. Dr. Owusu Afriyie Akoto","title":"Former Minister of Food and Agriculture","image":"/Picture3.png"}]',
    '[{"time":"9:00 AM","session":"Registration and Welcome"},{"time":"9:30 AM","session":"Opening Ceremony"},{"time":"10:30 AM","session":"Keynote: Market Resilience"},{"time":"12:00 PM","session":"Networking Lunch"},{"time":"1:30 PM","session":"Panel: Digital Transformation"},{"time":"3:00 PM","session":"Awards Ceremony"},{"time":"4:30 PM","session":"Closing Remarks"}]',
    '["Valid government-issued ID","Business card for networking"]',
    TRUE,
    FALSE
),
(
    'Agricultural Innovation Summit 2023',
    'agricultural-innovation-summit-2023',
    '2023-10-20',
    '8:00 AM - 6:00 PM',
    'Kumasi, Ghana',
    'Golden Tulip Kumasi City',
    'Asokore Mampong, Kumasi, Ghana',
    'Summit',
    'Summit',
    'completed',
    'Exploring digital agriculture and technology solutions for modern farming practices and commodity trading.',
    'The 2023 Agricultural Innovation Summit explored digital agriculture and technology solutions for modern farming practices. The event featured presentations from leading tech companies, practical demonstrations, and networking opportunities.',
    300,
    '/Picture3.png',
    FALSE,
    NULL,
    'GHS 30',
    '[]',
    '[]',
    '[]',
    TRUE,
    FALSE
),
(
    'Commodity Market Analysis Workshop 2023',
    'commodity-market-workshop-2023',
    '2023-08-10',
    '9:00 AM - 3:00 PM',
    'Tamale, Ghana',
    'Radach Lodge',
    'Tamale, Northern Region, Ghana',
    'Workshop',
    'Workshop',
    'completed',
    'Training workshop on commodity market analysis and trading strategies for local farmers and traders.',
    'A comprehensive workshop providing practical training on commodity market analysis and trading strategies.',
    150,
    '/Picture3.png',
    FALSE,
    NULL,
    'Free',
    '[]',
    '[]',
    '[]',
    TRUE,
    FALSE
);
